server:
  port: 8080

redis:
  addr: localhost:6379
  password: ""
  db: 0

cache:
  ttl: 5m

providers:
  osm:
    enabled: true
    weight: 10
    priority: 10

  google:
    enabled: false
    api_key: AIzaSyDA7JKapTieeSD7KUFFBfJG-rdvvR4_6yw
    weight: 10
    priority: 1