services:

  hynek-poi:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hynek-poi

    ports:
      - "8080:8080"

    depends_on:
      - redis

    environment:
      SERVER_PORT: 8080
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      CACHE_TTL: 5m

    restart: unless-stopped

    networks:
      - hynek-poi-network


  redis:
    image: redis:7-alpine

    container_name: hynek-poi-redis

    ports:
      - "6379:6379"

    volumes:
      - hynek-poi-redis-data:/data

    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

    restart: unless-stopped

    networks:
      - hynek-poi-network


  redis-insight:
    image: redis/redisinsight:latest

    container_name: hynek-poi-redis-insight

    ports:
      - "5540:5540"

    depends_on:
      - redis

    restart: unless-stopped

    networks:
      - hynek-poi-network

  prometheus:
    image: prom/prometheus

    container_name: hynek-poi-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - hynek-poi-network

  grafana:
    image: grafana/grafana:latest

    container_name: hynek-poi-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    restart: unless-stopped

    networks:
      - hynek-poi-network


volumes:
  hynek-poi-redis-data:
  grafana-data:


networks:
  hynek-poi-network:
    driver: bridge