version: "3.9"

services:

  redis:
    image: redis:7-alpine
    container_name: hynek-poi-redis

    ports:
      - "6379:6379"

    volumes:
      - hynek-poi-redis-data:/data

    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: hynek-poi-redis-insight

    ports:
      - "5540:5540"

    restart: unless-stopped

volumes:
  hynek-poi-redis-data: